//! Continuous human-input monitoring and the **Human Always Wins** contract.
//!
//! The runtime must react to real user input *while* an agent batch is
//! executing, not just afterwards by measuring pointer distance. This module
//! provides the platform-neutral [`HumanInputMonitor`]: macOS Event Taps feed
//! it via [`HumanInputSink`], and the action queue polls it between/within
//! actions. When a real human event arrives the monitor records the interrupt
//! latency and raises a takeover flag that only [`release`] can clear — a
//! plain `resume` can never bypass it (the session state machine already
//! enforces that).
//!
//! Synthetic events generated by the runtime itself never raise the flag:
//! macOS Event Taps identify the posting process, so a CGEvent whose source
//! PID is ours is treated as synthetic and skipped at the tap. The monitor
//! additionally tracks a short "synthetic window" as a conservative backstop
//! and exposes its metrics for tracing.

use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Mutex;
use std::time::{Duration, Instant};

/// Number of consecutive actions without a takeover requested after which the
/// monitor considers the user idle again (used by tests to reset state).
pub const TAKEOVER_RESET_AFTER_IDLE_SECS: u64 = 30;

/// A sink that receives real human input events. Implemented by the
/// platform-neutral [`HumanInputMonitor`]; the macOS Event Tap driver holds an
/// `Arc<dyn HumanInputSink>` and calls [`on_human_event`] for every real
/// (non-synthetic) user event.
pub trait HumanInputSink: Send + Sync {
    /// A real human input event was observed. `latency_ms` is the measured
    /// time from the event timestamp to the moment the runtime noticed.
    fn on_human_event(&self, latency_ms: u64);
}

/// Continuous human-input detector shared by the runtime and the macOS driver.
///
/// - `on_human_event` should be called by the platform input tap as soon as a
///   real event is seen.
/// - `takeover_requested` reports whether a takeover is pending.
/// - `consume_takeover` atomically clears the pending flag and returns whether
///   the batch must stop **now** (Human Always Wins).
pub struct HumanInputMonitor {
    last_human: Mutex<Option<Instant>>,
    pending_takeover: AtomicBool,
    last_latency_ms: Mutex<Option<u64>>,
    /// Recent synthetic events (for diagnostics only; the tap itself already
    /// filters by source PID).
    synthetic_count: std::sync::atomic::AtomicU64,
}

impl Default for HumanInputMonitor {
    fn default() -> Self {
        Self::new()
    }
}

impl HumanInputMonitor {
    pub fn new() -> Self {
        Self {
            last_human: Mutex::new(None),
            pending_takeover: AtomicBool::new(false),
            last_latency_ms: Mutex::new(None),
            synthetic_count: std::sync::atomic::AtomicU64::new(0),
        }
    }

    /// True when a takeover is pending (a real user event arrived since the
    /// last `consume_takeover`/`reset`).
    pub fn takeover_requested(&self) -> bool {
        self.pending_takeover.load(Ordering::SeqCst)
    }

    /// Atomically consume the pending takeover flag. Returns true *and clears*
    /// the flag, or false when nothing was pending. Call this before starting
    /// each action and inside every wait loop — when it returns true the batch
    /// must stop immediately and the session must enter `UserTakeover`.
    pub fn consume_takeover(&self) -> bool {
        self.pending_takeover.swap(false, Ordering::SeqCst)
    }

    /// Clear all state (called when a session starts or releases control).
    pub fn reset(&self) {
        self.pending_takeover.store(false, Ordering::SeqCst);
        *self.last_human.lock().unwrap() = None;
        *self.last_latency_ms.lock().unwrap() = None;
        self.synthetic_count.store(0, Ordering::SeqCst);
    }

    /// Record a real human event. `event_instant` should be the event's own
    /// timestamp so the latency is measured from the input, not the poll.
    pub fn record_human_event(&self, event_instant: Instant) {
        let latency_ms = event_instant.elapsed().as_millis().min(u64::MAX as u128) as u64;
        *self.last_human.lock().unwrap() = Some(Instant::now());
        *self.last_latency_ms.lock().unwrap() = Some(latency_ms);
        self.pending_takeover.store(true, Ordering::SeqCst);
    }

    /// Record that a synthetic (runtime-posted) event was seen by the tap;
    /// this never raises the takeover flag, it only feeds diagnostics.
    pub fn record_synthetic(&self) {
        self.synthetic_count.fetch_add(1, Ordering::SeqCst);
    }

    /// Last measured human-interrupt latency in ms, if any.
    pub fn last_latency_ms(&self) -> Option<u64> {
        *self.last_latency_ms.lock().unwrap()
    }

    /// Number of synthetic events seen (diagnostics).
    pub fn synthetic_count(&self) -> u64 {
        self.synthetic_count.load(Ordering::SeqCst)
    }

    /// Seconds since the last human event (or `None` if none observed yet).
    pub fn idle_secs(&self) -> Option<u64> {
        self.last_human
            .lock()
            .unwrap()
            .map(|t| t.elapsed().as_secs())
    }
}

impl HumanInputSink for HumanInputMonitor {
    fn on_human_event(&self, latency_ms: u64) {
        *self.last_human.lock().unwrap() = Some(Instant::now());
        *self.last_latency_ms.lock().unwrap() = Some(latency_ms);
        self.pending_takeover.store(true, Ordering::SeqCst);
    }
}

/// Convenience time window used to decide whether a pointer jump is human:
/// anything arriving within this window of a synthetic post is treated as
/// part of our own motion (conservative, prevents self-triggering).
pub const SYNTHETIC_WINDOW: Duration = Duration::from_millis(20);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn human_event_raises_takeover_and_consumes() {
        let m = HumanInputMonitor::new();
        assert!(!m.takeover_requested());
        m.record_human_event(Instant::now());
        assert!(m.takeover_requested());
        assert!(m.consume_takeover());
        assert!(!m.takeover_requested());
        assert!(!m.consume_takeover());
    }

    #[test]
    fn synthetic_events_never_raise_takeover() {
        let m = HumanInputMonitor::new();
        m.record_synthetic();
        m.record_synthetic();
        assert!(!m.takeover_requested());
        assert_eq!(m.synthetic_count(), 2);
        assert!(m.last_latency_ms().is_none());
    }

    #[test]
    fn latency_is_recorded() {
        let m = HumanInputMonitor::new();
        // Simulate an event that happened 5ms ago.
        m.record_human_event(Instant::now() - Duration::from_millis(5));
        let lat = m.last_latency_ms().unwrap();
        assert!((5..1000).contains(&lat), "unexpected latency {lat}");
    }

    #[test]
    fn reset_clears_pending() {
        let m = HumanInputMonitor::new();
        m.record_human_event(Instant::now());
        assert!(m.takeover_requested());
        m.reset();
        assert!(!m.takeover_requested());
        assert!(m.last_latency_ms().is_none());
    }

    #[test]
    fn sink_trait_contract() {
        let m = HumanInputMonitor::new();
        let sink: &dyn HumanInputSink = &m;
        sink.on_human_event(3);
        assert!(m.takeover_requested());
        assert_eq!(m.last_latency_ms(), Some(3));
    }
}
